join_rooms:
- pin: qwe
  rid: iQvRjLPS
- pin: qwe
  rid: XeSi2Rpq
- pin: qwe
  rid: 9M1t7bXH
test_users:
- password: tmppassword
  username: p_13304936695
- password: tmppassword
  username: p_13304936695_player1
- password: twppassword
  username: p_13304936695_player2
- password: twppassword
  username: p_13304936695_player3
- password: twppassword
  username: p_13304936695_player4
- password: twppassword
  username: p_13304936695_player5
